# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  masterclasswebapi:
    image: masterclasswebapi
    build:
      context: .
      dockerfile: src/MasterClass.WebApi/Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=$CERT_PASSWORD
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/$CERT_FILENAME
